Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.hostname = "Assia-vagrant"

  # SSH port forwarding
  config.vm.network "forwarded_port",
    guest: 1111,
    host: 1111,
    id: "ssh",
    auto_correct: true,
    host_ip: "127.0.0.1"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 1
  end

#config.vm.boot_timeout= 600
	
	
  # Provisioning scripts
  config.vm.provision "shell", path: "scripts/base.sh"
  #config.vm.provision "shell", path: "scripts/ssh.sh"
  config.vm.provision "shell", path: "scripts/users.sh"
  #config.vm.provision "shell", path: "scripts/firewall.sh"
  config.vm.provision "shell", path: "scripts/password-policy.sh"
  config.vm.provision "shell", path: "scripts/sudo-logging.sh"
  config.vm.provision "shell", path: "scripts/monitoring.sh"
  config.vm.provision "shell", path: "scripts/service.sh"
end
